"""add names

Revision ID: 730621fab04f
Revises: 8ce1f96e1a6f
Create Date: 2025-10-02 17:52:31.083707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730621fab04f'
down_revision: Union[str, Sequence[str], None] = '8ce1f96e1a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('list_name', sa.String(length=64), nullable=False))
    op.add_column('tasks', sa.Column('task_name', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_name')
    op.drop_column('lists', 'list_name')
    # ### end Alembic commands ###
